import requests

API_URL = "https://imgapi-66o65w2gbq-et.a.run.app"  # Replace with your server URL

# Assuming you have the ID token available
id_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjJkM2E0YTllYjY0OTk0YzUxM2YyYzhlMGMwMTY1MzEzN2U5NTg3Y2EiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY2Fwc3RvbmUtbnV0cmlzZWUiLCJhdWQiOiJjYXBzdG9uZS1udXRyaXNlZSIsImF1dGhfdGltZSI6MTY4NTI5NTkzNiwidXNlcl9pZCI6IkY1U2x0N1JMbE9Od2J5OU9wNXlBYlA2NEJYbTIiLCJzdWIiOiJGNVNsdDdSTGxPTndieTlPcDV5QWJQNjRCWG0yIiwiaWF0IjoxNjg1Mjk1OTM2LCJleHAiOjE2ODUyOTk1MzYsImVtYWlsIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJleGFtcGxlQGV4YW1wbGUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiY3VzdG9tIn19.k1xFmqL49EXtbhsdhF-jo9AF6DDGPtgom07ec2JPhDHgVBDzqpvG1ui2ANyZw_mJHoe3HtTVEb_k9mVux4JtsNkRb21cJRT6NCU_3eT7lGqV_pmLFS1xy9PIV1f6KrYguihSQCNKLkiOIOJVBHCdyBQ2vLUuxCOTRDrw3_VLXYU9Tdcgabmghp4UcUEhXtvGXotp-2ARNfjL8hXmpKuwBekrqs0y7NUSwqRzYWJlbVpyzofmmiAsNTVYdYIqou3OTMOoeJg4YhCYYHKVJPbT09QKBmVm0XIrJN4Rpqha_kk5NjCTjct9XuPAavQlaz4a-PonOTPgrbir4Z7ntdeNkA"

headers = {
    "Authorization": id_token
}

# Send POST request to log out the user
response = requests.post(f"{API_URL}/logout", headers=headers)

# Check the response status code
if response.status_code == 200:
    print("User logged out successfully")
else:
    print("Logout error:", response.json().get('error'))
